---
title: "Tidy Exp"
author: "Anish Yakkala"
date: "3/7/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
text <- c("Because I could not stop for Death -",
          "He kindly stopped for me -",
          "The Carriage held but just Ourselves -",
          "and Immortality")

text
```
```{r}
library(dplyr)
```
```{r}
text_df <- tibble(line = 1:4, text = text)
```

```{r}
library(tidytext)
```

```{r}
text_df %>%
  unnest_tokens(word,text)
```

```{r}
library(janeaustenr)
library(dplyr)
library(stringr)
```

```{r}
original_books <- austen_books() %>%
  group_by(book) %>%
  mutate(linenumber = row_number(),
         chapter = cumsum(str_detect(text, regex("^chapter [\\divxlc]",
                                                 ignore_case = TRUE)))) %>%
  ungroup()

original_books
```
```{r}
tidy_books <- original_books %>%
    unnest_tokens(word,text)

tidy_books
```

```{r}
data(stop_words)

tidy_books <- tidy_books %>%
  anti_join(stop_words)


```
```{r}
tidy_books %>%
  count(word, sort = TRUE)
```

```{r}
library(ggplot2)
```
```{r}
tidy_books %>%
  count(word, sort = TRUE) %>%
  filter(n > 600) %>%
  mutate(word = reorder(word, n )) %>%
  ggplot(aes(word, n )) + geom_col() + xlab(NULL) + coord_flip()
```

## Gutenbergr

```{r}
library(gutenbergr)
```

```{r}
hgwells <- gutenberg_download(c(35,36,5230,159))
```

```{r}
tidy_hgwells <- hgwells %>%
  unnest_tokens(word, text) %>%
  anti_join(stop_words)
```
```{r}
tidy_hgwells %>%
  count(word, sort = TRUE)
```

